### ISSUE TITLE
Tool Proficiencies: Cook's Utensils added as a proficiency when selecting any tool

### ISSUE THREAD

**Issue by bushongj** [Astrotech89/ME5e-FoundryVTT#1]
When selecting any tool or kit as a tool proficiency from the character sheet, cook's utensils is added automatically and you cant remove it.

**Comment by Astrotech89** [comment]
Currently deleted item is commented out.  Need to investigate root cause

**Comment by bushongj** [comment]
Let me know if you need me to explain how I came to this solution.

**Comment by Astrotech89** [comment]
Cook's tools in already in 5e system.  The addition of the cook's tools in the ME5e module unnecessary and causes bugs
