### ISSUE TITLE
Add all omitted bestiary entries

### ISSUE THREAD

**Issue by sparkcity** [Astrotech89/ME5e-FoundryVTT#21]
In the original module, some entries were omitted because of copyright infringement fears. There are also some newer bestiary entries that haven't been added. These need to be added in:

- Adjutant
- Albino Kath Hand
- Collector Assassin
- Collector Captain
- Collector Drone
- Collector General
- Collector Guardian
- Collector Trooper
- Geth Armature
- Geth Bomber
- Geth Colossus
- Geth Hunter
- Geth Juggernaut
- Geth Prime
- Geth Stalker
- Geth Trooper
- Geth Turret
- Horned Kath Hound
- Kath Hound
- Kett Chosen
- Klixen
- N7 Demolisher
- N7 Paladin
- N7 Shadow
- N7 Slayer
- Rachni Brood Warrior
- Rachni Queen
- Rachni Soldier
- Rachni Worker
- Rampart Mech
- Salarian STG Agent
- Seeker Plague
- Seeker Swarm
- Sniper
- Thorian
- Thorian Controller
- Thorian Creeper
- Thorian Nymph
- Thorian Spawn
- Thorian Thrall
- Thresher Maw
- Varren
- Varren Alpha
- Weakened Adjutant

**Comment by bushongj** [comment]
I think you got most of them but my list has a few more: 

Adjutant
Albino Kath Hound
Assault Trooper
Atlas
Blood Pack Boom-Squad
Centurion
Collector Assasin
Collector Captain
Collector Drone
Collector General
Collector Guardian
Collector Trooper
Combat Drone
Combat Engineer
Geth Armature
Geth Bomber
Geth Colossus
Geth Hunter
Geth Prime
Geth Stalker
Geth Trooper
Geth Turret
Guardian
Harvester
Horned Kath Hound
Husk
Kath Hound
Kett Chosen
Klixen
Phantom
Praetorian
Pyjak
Rachni brood warrior
rachni queen
Rachni soldier
rachni worker
rampart mech
salarian STG Agent
security guard
seeker plague
seeker swarm
sentry turret
sniper
thorian
thorian controller
throian creeper
thorian Nymph
thorian span
thorian thrall thresher Maw
varren
varren alpha
weakened adjutant
Yahg

**Comment by sparkcity** [comment]
Security Guard, Guardian, Husk, Assault Trooper, Atlas, Blood Pack Boom-Squad, Centurion, turrets and drones are all in there, I just double checked so no worries.

**Comment by sparkcity** [comment]
Getting started on adding all other omitted entries
