### ISSUE TITLE
Original author

### ISSUE THREAD

**Issue by sparkcity** [Astrotech89/ME5e-FoundryVTT#7]
Hey, just wanted to let yall know that I've republished it here just so it can continue to be played and downloaded: https://github.com/sparkcity/fvtt-me5e

I'm happy to add yall as contributors or whatever's easiest for continuing to build and maintain it. Apologies for the confusion (and miscalculation on my part, genuinely didn't know anyone would notice if the module was gone).

**Comment by Astrotech89** [comment]
Hey Sparkcity!

Good to hear from you!  Glad it's up as well.  We've been working on a few updates on this so far but we should definitely work together on this!  What's the best way to DM you?

**Comment by sparkcity** [comment]
Super appreciate yall taking the baton for this! I'm happy to contribute and see what's being worked on and where I can help. I'm pretty reachable on discord, shouldn't have too much trouble though there might be delays during the work day. Once this module has a release, I can decommission my old module on Foundry and you can submit this one on there to replace it.

**Comment by Astrotech89** [comment]
Yeah no problem!  Looks like you got your hands full on other modules.  We've been trying to chip away at this but I'll admit my JavaScript is basically non-existent.  I've made a link to the discord server I start with the other contributer
https://discord.gg/e7W2tF9

If it's expired let me know and I'll drop another one
